baseurl = "http://proteusisc.org/"
languageCode = "en-us"
title = "ProteusISC - General In System Configuration"
theme = "purehugo"
#theme = "hugo-theme-learn"
#theme = "blackburn"
pygmentsuseclasses = true
